version: '3.9'
networks:
  myfiles:

services:
  myfiles:
    image: myfiles
    ports:
      - 8004:3000
    networks:
      - myfiles
    env_file:
      - .env
    restart: unless-stopped
    container_name: myfiles